#!/bin/sh
python createdb.py
python cuimingweb/manage.py syncdb --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
#python cuimingweb/manage.py collectstatic --noinput